include_recipe "../cookbooks/build_essential/default.rb"
include_recipe "../cookbooks/firewalld/default.rb"
include_recipe "../cookbooks/perl/default.rb"
include_recipe "../cookbooks/mariadb/default.rb"
include_recipe "../cookbooks/mogilefs/default.rb"
